[package]
name = "tapwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
chrono = "0.4"
rdev = "0.5"
base64 = "0.22"
once_cell = "1.19"
image = "0.25"
tui-big-text = "0.7"
rand = "0.8"
libc = "0.2"
